from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class ForeignPlaceMatch:
    host_country: str
    canonical_code: str
    canonical_name: str
    reason: str


_COUNTRY_EN_NAME: dict[str, str] = {
    "AF": "Afghanistan",
    "AM": "Armenia",
    "AL": "Albania",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BH": "Bahrain",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "EE": "Estonia",
    "LV": "Latvia",
    "BY": "Belarus",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CN": "China",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "DZ": "Algeria",
    "AE": "United Arab Emirates",
    "EG": "Egypt",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "GE": "Georgia",
    "GR": "Greece",
    "DO": "Dominican Republic",
    "HR": "Croatia",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IN": "India",
    "IE": "Ireland",
    "IS": "Iceland",
    "IL": "Israel",
    "IR": "Iran",
    "IT": "Italy",
    "JO": "Jordan",
    "JP": "Japan",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LB": "Lebanon",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LY": "Libya",
    "MA": "Morocco",
    "MD": "Moldova",
    "MK": "North Macedonia",
    "ME": "Montenegro",
    "MT": "Malta",
    "MY": "Malaysia",
    "MX": "Mexico",
    "MN": "Mongolia",
    "NG": "Nigeria",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "PA": "Panama",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "PS": "Palestine",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "SE": "Sweden",
    "SN": "Senegal",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SY": "Syria",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UZ": "Uzbekistan",
    "US": "United States",
    "VN": "Vietnam",
    "XK": "Kosovo",
    "ZA": "South Africa",
    "ET": "Ethiopia",
    "SG": "Singapore",
    "SA": "Saudi Arabia",
    "OM": "Oman",
    "KP": "North Korea",
}


def _norm_key(value: str | None) -> str:
    text = str(value or "").strip().casefold()
    text = re.sub(r"^(гр|с|кв|жк)\.?\s*", "", text)
    text = re.sub(r"[^\w]+", "", text, flags=re.UNICODE)
    return text


# BG 2009 foreign polling-station code prefixes (99......) -> host country ISO2.
_BG_2009_PREFIX_TO_HOST: dict[str, str] = {
    "9900001": "AU",  # Australia
    "9900002": "AT",
    "9900003": "AL",
    "9900004": "DZ",
    "9900005": "AF",
    "9900006": "BE",
    "9900007": "BA",
    "9900008": "GB",
    "9900009": "GR",
    "9900010": "DK",
    "9900011": "IL",
    "9900012": "IR",
    "9900013": "IE",
    "9900014": "ES",
    "9900015": "IT",
    "9900016": "KZ",
    "9900017": "CA",
    "9900018": "CY",
    "9900019": "CN",
    "9900020": "KR",
    "9900021": "XK",
    "9900022": "KW",
    "9900023": "LY",
    "9900024": "LB",
    "9900025": "LT",
    "9900026": "LU",
    "9900027": "MT",
    "9900028": "MA",
    "9900029": "MD",
    "9900030": "NG",
    "9900031": "NL",
    "9900032": "NO",
    "9900033": "AE",
    "9900034": "PL",
    "9900035": "PT",
    "9900036": "MK",
    "9900037": "ZA",
    "9900038": "RO",
    "9900039": "RU",
    "9900040": "US",
    "9900041": "SY",
    "9900042": "SK",
    "9900043": "SI",
    "9900044": "RS",
    "9900045": "TH",
    "9900046": "TN",
    "9900047": "TR","PL"
    "9900048": "UA",
    "9900049": "HU",
    "9900050": "FI",
    "9900051": "DE",
    "9900052": "FR",
    "9900053": "HR",
    "9900054": "CZ",
    "9900055": "CL",
    "9900056": "CH",
    "9900057": "SE",
    "9900058": "JP",
    "9900059": "NZ",
}


_BG_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("Австралия"): "AU",
    _norm_key("Австрия"): "AT",
    _norm_key("Азербайджан"): "AZ",
    _norm_key("Азърбайджан"): "AZ",
    _norm_key("Алжир"): "DZ",
    _norm_key("Армения"): "AM",
    _norm_key("Албания"): "AL",
    _norm_key("Аржентина"): "AR",
    _norm_key("Афганистан"): "AF",
    _norm_key("Белгия"): "BE",
    _norm_key("Босна и Херцеговина"): "BA",
    _norm_key("Великобритания"): "GB",
    _norm_key("Обединено кралство Великобритания и Северна Ирландия"): "GB",
    _norm_key("Обединеното кралство"): "GB",
    _norm_key("Германия"): "DE",
    _norm_key("ФР Германия"): "DE",
    _norm_key("Германия ФР"): "DE",
    _norm_key("Грузия"): "GE",
    _norm_key("Гърция"): "GR",
    _norm_key("Дания"): "DK",
    _norm_key("Египет"): "EG",
    _norm_key("Израел"): "IL",
    _norm_key("Ирландия"): "IE",
    _norm_key("Испания"): "ES",
    _norm_key("Италия"): "IT",
    _norm_key("Канада"): "CA",
    _norm_key("Катар"): "QA",
    _norm_key("Кипър"): "CY",
    _norm_key("Китай"): "CN",
    _norm_key("Корея"): "KR",
    _norm_key("Република Корея"): "KR",
    _norm_key("Косово"): "XK",
    _norm_key("Кралство Йордания"): "JO",
    _norm_key("Йордания"): "JO",
    _norm_key("Кувейт"): "KW",
    _norm_key("Ливан"): "LB",
    _norm_key("Люксембург"): "LU",
    _norm_key("Македония"): "MK",
    _norm_key("Република Македония"): "MK",
    _norm_key("Република Северна Македония"): "MK",
    _norm_key("Малта"): "MT",
    _norm_key("Малайзия"): "MY",
    _norm_key("Мароко"): "MA",
    _norm_key("Мексико"): "MX",
    _norm_key("Молдова"): "MD",
    _norm_key("Нова Зеландия"): "NZ",
    _norm_key("Нигерия"): "NG",
    _norm_key("Нидерландия"): "NL",
    _norm_key("Норвегия"): "NO",
    _norm_key("ОАЕ"): "AE",
    _norm_key("Обединени арабски емирства"): "AE",
    _norm_key("Полша"): "PL",
    _norm_key("Португалия"): "PT",
    _norm_key("Република Южна Африка"): "ZA",
    _norm_key("Черна гора"): "ME",
    _norm_key("Румъния"): "RO",
    _norm_key("Русия"): "RU",
    _norm_key("САЩ"): "US",
    _norm_key("Словакия"): "SK",
    _norm_key("Словения"): "SI",
    _norm_key("Сърбия"): "RS",
    _norm_key("Тунис"): "TN",
    _norm_key("Турция"): "TR",
    _norm_key("Украйна"): "UA",
    _norm_key("Узбекистан"): "UZ",
    _norm_key("Виетнам"): "VN",
    _norm_key("Индия"): "IN",
    _norm_key("Индонезия"): "ID",
    _norm_key("Иран"): "IR",
    _norm_key("Исландия"): "IS",
    _norm_key("Казахстан"): "KZ",
    _norm_key("Куба"): "CU",
    _norm_key("Беларус"): "BY",
    _norm_key("Бразилия"): "BR",
    _norm_key("Сингапур"): "SG",
    _norm_key("Саудитска арабия"): "SA",
    _norm_key("Саудитска Арабия"): "SA",
    _norm_key("Палестинска власт"): "PS",
    _norm_key("Доминиканска Република"): "DO",
    _norm_key("Бахрейн"): "BH",
    _norm_key("Унгария"): "HU",
    _norm_key("Финландия"): "FI",
    _norm_key("Франция"): "FR",
    _norm_key("Хърватия"): "HR",
    _norm_key("Чешка Република"): "CZ",
    _norm_key("Чешка република"): "CZ",
    _norm_key("Чехия"): "CZ",
    _norm_key("Швейцария"): "CH",
    _norm_key("Швеция"): "SE",
    _norm_key("Япония"): "JP",
}


_BG_CITY_ALIASES: dict[str, str] = {
    _norm_key("Канбера"): "AU",
    _norm_key("Сидни"): "AU",
    _norm_key("Виена"): "AT",
    _norm_key("Тирана"): "AL",
    _norm_key("Лондон"): "GB",
    _norm_key("Манчестър"): "GB",
    _norm_key("Атина"): "GR",
    _norm_key("Мадрид"): "ES",
    _norm_key("Рим"): "IT",
    _norm_key("Милано"): "IT",
    _norm_key("Никозия"): "CY",
    _norm_key("Пекин"): "CN",
    _norm_key("Шанхай"): "CN",
    _norm_key("Варшава"): "PL",
    _norm_key("Лисабон"): "PT",
    _norm_key("Москва"): "RU",
    _norm_key("Париж"): "FR",
    _norm_key("Прага"): "CZ",
    _norm_key("Женева"): "CH",
    _norm_key("Цюрих"): "CH",
    _norm_key("Стокхолм"): "SE",
    _norm_key("Токио"): "JP",
    _norm_key("Истанбул"): "TR",
    _norm_key("Анкара"): "TR",
    _norm_key("Киев"): "UA",
    _norm_key("Одеса"): "UA",
    _norm_key("Берлин"): "DE",
    _norm_key("Хамбург"): "DE",
    _norm_key("Франкфурт"): "DE",
    _norm_key("Марсилия"): "FR",
    _norm_key("Лион"): "FR",
    _norm_key("Брюксел"): "BE",
    _norm_key("Антверпен"): "BE",
    _norm_key("Гент"): "BE",
    _norm_key("Амстердам"): "NL",
    _norm_key("Хага"): "NL",
    _norm_key("Ротердам"): "NL",
    _norm_key("Будапеща"): "HU",
    _norm_key("Осло"): "NO",
    _norm_key("Дубай"): "AE",
    _norm_key("Братислава"): "SK",
    _norm_key("Любляна"): "SI",
    _norm_key("Белград"): "RS",
    _norm_key("Загреб"): "HR",
    _norm_key("Тунис"): "TN",
    _norm_key("Люксембург"): "LU",
    _norm_key("Прищина"): "XK",
    _norm_key("Хелзинки"): "FI",
    _norm_key("Страсбург"): "FR",
    _norm_key("Тулуза"): "FR",
    _norm_key("Бордо"): "FR",
    _norm_key("Ница"): "FR",
    _norm_key("Лил"): "FR",
    _norm_key("Монпелие"): "FR",
    _norm_key("Сен Луи"): "FR",
    _norm_key("Мюнхен"): "DE",
    _norm_key("Магдебург"): "DE",
    _norm_key("Бон"): "DE",
    # Austria
    _norm_key("Брегенц"): "AT",
    _norm_key("Винер Нойщат"): "AT",
    # Afghanistan
    _norm_key("Кабул"): "AF",
    # United Kingdom
    _norm_key("Манчестер"): "GB",
    _norm_key("Флиитхампшир"): "GB",
    _norm_key("Глазгоу"): "GB",
    _norm_key("Дънди"): "GB",
    _norm_key("Абърдийн"): "GB",
    _norm_key("Бирмингам"): "GB",
    _norm_key("Единбург"): "GB",
    _norm_key("Колчестер"): "GB",
    _norm_key("Чатам"): "GB",
    _norm_key("Честър"): "GB",
    _norm_key("Бристол"): "GB",
    _norm_key("Ковънтри"): "GB",
    # Greece
    _norm_key("Солун"): "GR",
    _norm_key("Александруполис"): "GR",
    _norm_key("Волос"): "GR",
    _norm_key("Йерапетра"): "GR",
    _norm_key("Кавала"): "GR",
    _norm_key("Родос"): "GR",
    _norm_key("Патра"): "GR",
    _norm_key("Ханя"): "GR",
    # Denmark
    _norm_key("Копенхаген"): "DK",
    _norm_key("Орхус"): "DK",
    _norm_key("Олборг"): "DK",
    # Ireland
    _norm_key("Дъблин"): "IE",
    # Spain
    _norm_key("Аранда де Дуеро"): "ES",
    _norm_key("Уеркал-Овера"): "ES",
    _norm_key("Барселона"): "ES",
    _norm_key("Валенсия"): "ES",
    _norm_key("Бургос"): "ES",
    _norm_key("Валядолид"): "ES",
    _norm_key("Колядо Вилялба"): "ES",
    _norm_key("Куеляр"): "ES",
    _norm_key("Палма де Майорка"): "ES",
    _norm_key("Искар"): "ES",
    _norm_key("Нава де ла Асунсион"): "ES",
    _norm_key("Памплона"): "ES",
    _norm_key("Сеговия"): "ES",
    _norm_key("Аликанте"): "ES",
    _norm_key("Гандия"): "ES",
    _norm_key("Енгера"): "ES",
    _norm_key("Мурсия"): "ES",
    _norm_key("Марбеля"): "ES",
    _norm_key("Торемолинос"): "ES",
    _norm_key("Алкала де Енарес"): "ES",
    _norm_key("Мостолес"): "ES",
    _norm_key("Бенидорм"): "ES",
    _norm_key("Ел Елхидо"): "ES",
    _norm_key("Кастейон"): "ES",
    _norm_key("Сарагоса"): "ES",
    _norm_key("Таррагона"): "ES",
    _norm_key("Торревиеха"): "ES",
    _norm_key("Хатива"): "ES",
    _norm_key("Хетафе"): "ES",
    _norm_key("Канталехо"): "ES",
    _norm_key("Йорет де Мар"): "ES",
    _norm_key("Лорка"): "ES",
    _norm_key("Малага"): "ES",
    _norm_key("Реус"): "ES",
    _norm_key("Риаса"): "ES",
    _norm_key("Тафая"): "ES",
    _norm_key("Ивиса"): "ES",
    _norm_key("Пеняфиел"): "ES",
    # Italy
    _norm_key("Кастелмаре ди Сабия"): "IT",
    _norm_key("Неапол"): "IT",
    # Cyprus
    _norm_key("Полис-Хрисохус"): "CY",
    _norm_key("Пафос"): "CY",
    _norm_key("Лимасол"): "CY",
    _norm_key("Ларнака"): "CY",
    _norm_key("Паралимини"): "CY",
    # Lebanon
    _norm_key("Бейрут"): "LB",
    # North Macedonia
    _norm_key("Битоля"): "MK",
    _norm_key("Скопие"): "MK",
    # Malta
    _norm_key("Сейнт Джулиан"): "MT",
    # Moldova
    _norm_key("Кишинев"): "MD",
    # Netherlands
    _norm_key("Розендал"): "NL",
    _norm_key("Утрехт"): "NL",
    _norm_key("Керкдрийл"): "NL",
    # Poland
    _norm_key("Ленкница"): "PL",
    # Romania
    _norm_key("Букурещ"): "RO",
    # United States
    _norm_key("Ню Йорк"): "US",
    # Finland
    _norm_key("Хелзинки"): "FI",
    _norm_key("Тампере"): "FI",
    # Czech Republic
    _norm_key("Бърно"): "CZ",
    # Sweden
    _norm_key("Малмьо"): "SE",
    _norm_key("Гьотеборг"): "SE",
    # Switzerland
    _norm_key("Берн"): "CH",
}

_PT_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("Turquia"): "TR",
    _norm_key("Suíça"): "CH",
    _norm_key("Suécia"): "SE",
    _norm_key("Rússia"): "RU",
    _norm_key("Roménia"): "RO",
    _norm_key("República Checa"): "CZ",
    _norm_key("Reino Unido"): "GB",
    _norm_key("Polónia"): "PL",
    _norm_key("Noruega"): "NO",
    _norm_key("Luxemburgo"): "LU",
    _norm_key("Itália"): "IT",
    _norm_key("Irlanda"): "IE",
    _norm_key("Hungria"): "HU",
    _norm_key("Holanda"): "NL",
    _norm_key("Grécia"): "GR",
    _norm_key("França"): "FR",
    _norm_key("Finlândia"): "FI",
    _norm_key("Espanha"): "ES",
    _norm_key("Dinamarca"): "DK",
    _norm_key("Chipre"): "CY",
    _norm_key("Bulgária"): "BG",
    _norm_key("Bélgica"): "BE",
    _norm_key("Áustria"): "AT",
    _norm_key("Andorra"): "AD",
    _norm_key("Alemanha"): "DE",
    _norm_key("Timor"): "TL",
    _norm_key("Tailândia"): "TH",
    _norm_key("Singapura"): "SG",
    _norm_key("Qatar"): "QA",
    _norm_key("Japão"): "JP",
    _norm_key("Israel"): "IL",
    _norm_key("Indonésia"): "ID",
    _norm_key("Índia"): "IN",
    _norm_key("Emiratos Árabes Unidos"): "AE",
    _norm_key("China"): "CN",
    _norm_key("Austrália"): "AU",
    _norm_key("Arábia Saudita"): "SA",
    _norm_key("Venezuela"): "VE",
    _norm_key("Uruguai"): "UY",
    _norm_key("Peru"): "PE",
    _norm_key("Panamá"): "PA",
    _norm_key("México"): "MX",
    _norm_key("Estados Unidos Da América"): "US",
    _norm_key("Colômbia"): "CO",
    _norm_key("Chile"): "CL",
    _norm_key("Canadá"): "CA", 
    _norm_key("Brasil"): "BR",
    _norm_key("Argentina"): "AR",
    _norm_key("Zimbabwe"): "ZW",
    _norm_key("Senegal"): "SN",
    _norm_key("São Tomé E Príncipe"): "ST",
    _norm_key("República Democrática Do Congo"): "CD",
    _norm_key("Namíbia"): "NA",
    _norm_key("Moçambique"): "MZ",
    _norm_key("Marrocos"): "MA",
    _norm_key("Guiné-Bissau"): "GW",
    _norm_key("Cabo Verde"): "CV",
    _norm_key("Angola"): "AO",
    _norm_key("África Do Sul"): "ZA",
    _norm_key("Sérvia"): "RS",
    _norm_key("Reino Unido da Grã-bretanha e Irlanda do Norte"): "GB",
    _norm_key("Países Baixos"): "NL",
    _norm_key("Federação da Rússia"): "RU",
    _norm_key("Eslováquia"): "SK",
    _norm_key("Croácia"): "HR",
    _norm_key("Chéquia"): "CZ",
    _norm_key("Timor-leste"): "TL",
    _norm_key("Emirados Árabes Unidos"): "AE",
    _norm_key("Coreia (República da)"): "KR",
    _norm_key("Catar"): "QA",
    _norm_key("Venezuela (República Bolivariana da)"): "VE",
    _norm_key("Zimbabué"): "ZW",
    _norm_key("Tunísia"): "TN",
    _norm_key("Quénia"): "KE",
    _norm_key("Etiópia"): "ET",
    _norm_key("Costa do Marfim"): "CI",
    _norm_key("Congo (República Democrática do)"): "CD",
}

_HR_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("AFGANISTAN"): "AF",
    _norm_key("ALBANIJA"): "AL",
    _norm_key("ARGENTINA"): "AR",
    _norm_key("AUSTRALIJA"): "AU",
    _norm_key("AUSTRIJA"): "AT",
    _norm_key("BELGIJA"): "BE",
    _norm_key("BOSNA I HERCEGOVINA"): "BA",
    _norm_key("BRAZIL"): "BR",
    _norm_key("BUGARSKA"): "BG",
    _norm_key("CRNA GORA"): "ME",
    _norm_key("DANSKA"): "DK",
    _norm_key("EGIPAT"): "EG",
    _norm_key("FINSKA"): "FI",
    _norm_key("FRANCUSKA"): "FR",
    _norm_key("GRČKA"): "GR",
    _norm_key("INDIJA"): "IN",
    _norm_key("INDONEZIJA"): "ID",
    _norm_key("IRSKA"): "IE",
    _norm_key("ITALIJA"): "IT",
    _norm_key("IZRAEL"): "IL",
    _norm_key("JAPAN"): "JP",
    _norm_key("JUŽNOAFRIČKA REPUBLIKA"): "ZA",
    _norm_key("KANADA"): "CA",
    _norm_key("KATAR"): "QA",
    _norm_key("KINA"): "CN",
    _norm_key("KOSOVO"): "XK",
    _norm_key("LIBANON"): "LB",
    _norm_key("MAĐARSKA"): "HU",
    _norm_key("NIZOZEMSKA"): "NL",
    _norm_key("NJEMAČKA"): "DE",
    _norm_key("NORVEŠKA"): "NO",
    _norm_key("POLJSKA"): "PL",
    _norm_key("PORTUGAL"): "PT",
    _norm_key("RUMUNJSKA"): "RO",
    _norm_key("RUSIJA"): "RU",
    _norm_key("SAD"): "US",
    _norm_key("SJEVERNA MAKEDONIJA"): "MK",
    _norm_key("SLOVAČKA"): "SK",
    _norm_key("SLOVAČKA REPUBLIKA"): "SK",
    _norm_key("SLOVENIJA"): "SI",
    _norm_key("SRBIJA"): "RS",
    _norm_key("TURSKA"): "TR",
    _norm_key("UKRAJINA"): "UA",
    _norm_key("VELIKA BRITANIJA"): "GB",
    _norm_key("ČEŠKA REPUBLIKA"): "CZ",
    _norm_key("ČILE"): "CL",
    _norm_key("ŠPANJOLSKA"): "ES",
    _norm_key("ŠVEDSKA"): "SE",
    _norm_key("ŠVICARSKA"): "CH",
    _norm_key("LITVA"): "LT",
    _norm_key("REPUBLIKA SJEVERNA MAKEDONIJA"): "MK",
    _norm_key("UJEDINJENI ARAPSKI EMIRATI"): "AE",
}

_PL_COUNTRY_ALIASES: dict[str, str] = {    
    _norm_key("Zjednoczone Emiraty Arabskie"): "AE",
    _norm_key("Afganistan"): "AF",
    _norm_key("Albania"): "AL",
    _norm_key("Armenia"): "AM",
    _norm_key("Angola"): "AO",
    _norm_key("Argentyna"): "AR",
    _norm_key("Austria"): "AT",
    _norm_key("Australia"): "AU",
    _norm_key("Azerbejdżan"): "AZ",
    _norm_key("Bonia i Hercegowina"): "BA",
    _norm_key("Bośnia i Hercegowina"): "BA",
    _norm_key("Belgia"): "BE",
    _norm_key("Bułgaria"): "BG",
    _norm_key("Brazylia"): "BR",
    _norm_key("Białoru"): "BY",
    _norm_key("Białoruś"): "BY",
    _norm_key("Kanada"): "CA",
    _norm_key("Szwajcaria"): "CH",
    _norm_key("Chile"): "CL",
    _norm_key("Chińska Republika Ludowa"): "CN",
    _norm_key("Chiny"): "CN",
    _norm_key("Kolumbia"): "CO",
    _norm_key("Kuba"): "CU",
    _norm_key("Cypr"): "CY",
    _norm_key("Czechy"): "CZ",
    _norm_key("Niemcy"): "DE",
    _norm_key("Dania"): "DK",
    _norm_key("Algieria"): "DZ",
    _norm_key("Estonia"): "EE",
    _norm_key("Egipt"): "EG",
    _norm_key("Hiszpania"): "ES",
    _norm_key("Finlandia"): "FI",
    _norm_key("Francja"): "FR",
    _norm_key("Wielka Brytania"): "GB",
    _norm_key("Gruzja"): "GE",
    _norm_key("Grecja"): "GR",
    _norm_key("Chorwacja"): "HR",
    _norm_key("Węgry"): "HU",
    _norm_key("Indonezja"): "ID",
    _norm_key("Irlandia"): "IE",
    _norm_key("Izrael"): "IL",
    _norm_key("Indie"): "IN",
    _norm_key("Irak"): "IQ",
    _norm_key("Iran"): "IR",
    _norm_key("Islandia"): "IS",
    _norm_key("Włochy"): "IT",
    _norm_key("Jordania"): "JO",
    _norm_key("Japonia"): "JP",
    _norm_key("Kenia"): "KE",
    _norm_key("Korea Północna"): "KP",
    _norm_key("Korea Południowa"): "KR",
    _norm_key("Kuwejt"): "KW",
    _norm_key("Kazachstan"): "KZ",
    _norm_key("Liban"): "LB",
    _norm_key("Litwa"): "LT",
    _norm_key("Luksemburg"): "LU",
    _norm_key("Łotwa"): "LV",
    _norm_key("Libia"): "LY",
    _norm_key("Maroko"): "MA",
    _norm_key("Mołdawia"): "MD",
    _norm_key("Macedonia"): "MK",
    _norm_key("Macedonia Północna"): "MK",
    _norm_key("Czarnogóra"): "ME",
    _norm_key("Malta"): "MT",
    _norm_key("Mongolia"): "MN",
    _norm_key("Meksyk"): "MX",
    _norm_key("Malezja"): "MY",
    _norm_key("Nigeria"): "NG",
    _norm_key("Holandia"): "NL",
    _norm_key("Norwegia"): "NO",
    _norm_key("Nowa Zelandia"): "NZ",
    _norm_key("Oman"): "OM",
    _norm_key("Peru"): "PE",
    _norm_key("Panama"): "PA",
    _norm_key("Pakistan"): "PK",
    _norm_key("Portugalia"): "PT",
    _norm_key("Katar"): "QA",
    _norm_key("Rumunia"): "RO",
    _norm_key("Rosja"): "RU",
    _norm_key("Arabia Saudyjska"): "SA",
    _norm_key("Szwecja"): "SE",
    _norm_key("Senegal"): "SN",
    _norm_key("Singapur"): "SG",
    _norm_key("Słowenia"): "SI",
    _norm_key("Słowacja"): "SK",
    _norm_key("Syria"): "SY",
    _norm_key("Czad"): "TD",
    _norm_key("Tajlandia"): "TH",
    _norm_key("Tanzania"): "TZ",
    _norm_key("Turkmenistan"): "TM",
    _norm_key("Tunezja"): "TN",
    _norm_key("Turcja"): "TR",
    _norm_key("Tajpej"): "TW",
    _norm_key("Miasto Tajpej"): "TW",
    _norm_key("Ukraina"): "UA",
    _norm_key("Stany Zjednoczone Ameryki"): "US",
    _norm_key("Stany Zjednoczone"): "US",
    _norm_key("Uzbekistan"): "UZ",
    _norm_key("Wenezuela"): "VE",
    _norm_key("Wietnam"): "VN",
    _norm_key("Jemen"): "YE",
    _norm_key("Republika Południowej Afryki"): "ZA",
    _norm_key("Południowa Afryka"): "ZA",
    _norm_key("Etiopia"): "ET",
    _norm_key("Filipiny"): "PH",
    _norm_key("Serbia"): "RS",
    _norm_key("Kosovo"): "XK",
    _norm_key("Kosowo"): "XK",
    # Additional aliases
    _norm_key("RPA"): "ZA",           # Republika Południowej Afryki abbreviation
    _norm_key("Urugwaj"): "UY",
    _norm_key("Kongo"): "CD",
    _norm_key("Korea"): "KR",
    _norm_key("Kostaryka"): "CR",
    _norm_key("Ciny"): "CN",          # typo for Chiny
    _norm_key("Sułgaria"): "BG",      # typo for Bułgaria
    _norm_key("Serbia i Czarnogóra"): "CS",   # legacy Serbia and Montenegro
    _norm_key("Wielka Brytania i Irlandia"): "GB",
    _norm_key("Stany Zjednoczone II"): "US",
    _norm_key("Singapur"): "SG",
    _norm_key("Tajlandia"): "TH",
    _norm_key("Tajpej"): "TW",
    _norm_key("Tanzania"): "TZ",
    _norm_key("Włochy"): "IT",
}

# Polish-language city names → host country ISO-2.
# Used when the raw source encodes polling-station city as the row identifier.
_PL_CITY_ALIASES: dict[str, str] = {
    _norm_key("Aberdeen"): "GB",
    _norm_key("Abu Zabi"): "AE",
    _norm_key("Abudża"): "NG",
    _norm_key("Addis Abeba"): "ET",
    _norm_key("Algier"): "DZ",
    _norm_key("Amman"): "JO",
    _norm_key("Ankara"): "TR",
    _norm_key("Antwerpia"): "BE",
    _norm_key("Astana"): "KZ",
    _norm_key("Ateny"): "GR",
    _norm_key("Ałmaty"): "KZ",
    _norm_key("Baghdad"): "IQ",
    _norm_key("Bagram"): "AF",
    _norm_key("Bagram - Polish Military Camp"): "AF",
    _norm_key("Baku"): "AZ",
    _norm_key("Barcelona"): "ES",
    _norm_key("Bejrut"): "LB",
    _norm_key("Belfast"): "GB",
    _norm_key("Belgrad"): "RS",
    _norm_key("Bergen"): "NO",
    _norm_key("Berlin"): "DE",
    _norm_key("Berno"): "CH",
    _norm_key("Birmingham"): "GB",
    _norm_key("Bogota"): "CO",
    _norm_key("Brasilia"): "BR",
    _norm_key("Bratysława"): "SK",
    _norm_key("Bristol"): "GB",
    _norm_key("Bruksela"): "BE",
    _norm_key("Brześć"): "BY",
    _norm_key("Budapeszt"): "HU",
    _norm_key("Buenos Aires"): "AR",
    _norm_key("Bukareszt"): "RO",
    _norm_key("Calgary"): "CA",
    _norm_key("Canberra"): "AU",
    _norm_key("Caracas"): "VE",
    _norm_key("Cardiff"): "GB",
    _norm_key("Chicago"): "US",
    _norm_key("Doha"): "QA",
    _norm_key("Dublin"): "IE",
    _norm_key("Durban"): "ZA",
    _norm_key("Dżakarta"): "ID",
    _norm_key("Edmonton"): "CA",
    _norm_key("Edynburg"): "GB",
    _norm_key("Erywań"): "AM",
    _norm_key("Eurajoki"): "FI",
    _norm_key("Glasgow"): "GB",
    _norm_key("Grodno"): "BY",
    _norm_key("Göteborg"): "SE",
    _norm_key("Haga"): "NL",
    _norm_key("Hamburg"): "DE",
    _norm_key("Hamtramck"): "US",
    _norm_key("Hanoi"): "VN",
    _norm_key("Hawana"): "CU",
    _norm_key("Helsinki"): "FI",
    _norm_key("Heraklion"): "GR",
    _norm_key("Hongkong"): "HK",
    _norm_key("Hotel KENZI EUROPA"): "MA",
    _norm_key("Maroko"): "MA",
    _norm_key("Maroko,Rabat"): "MA",
    _norm_key("Maroko, Rabat"): "MA",
    _norm_key("Irbil"): "IQ",
    _norm_key("Irkuck"): "RU",
    _norm_key("Islamabad"): "PK",
    _norm_key("Kabul"): "AF",
    _norm_key("Kair"): "EG",
    _norm_key("Kaliningrad"): "RU",
    _norm_key("Kanton"): "CN",
    _norm_key("Kapsztad"): "ZA",
    _norm_key("Kijów"): "UA",
    _norm_key("Kiszyniów"): "MD",
    _norm_key("Kolonia"): "DE",
    _norm_key("Kopenhaga"): "DK",
    _norm_key("Kuala Lumpur"): "MY",
    _norm_key("Kurytyba"): "BR",
    _norm_key("Kuwejt"): "KW",
    _norm_key("Leeds"): "GB",
    _norm_key("Lens"): "FR",
    _norm_key("Lima"): "PE",
    _norm_key("Lisbona"): "PT",
    _norm_key("Londyn"): "GB",
    _norm_key("Los Angeles"): "US",
    _norm_key("Luanda"): "AO",
    _norm_key("Lublana"): "SI",
    _norm_key("Luksemburg"): "LU",
    _norm_key("Lyon"): "FR",
    _norm_key("Madryt"): "ES",
    _norm_key("Malaga"): "ES",
    _norm_key("Malmö"): "SE",
    _norm_key("Malmö Studiefrämjandet"): "SE",
    _norm_key("Manchester"): "GB",
    _norm_key("Mediolan"): "IT",
    _norm_key("Meksyk"): "MX",
    _norm_key("Mińsk"): "BY",
    _norm_key("Monachium"): "DE",
    _norm_key("Montreal"): "CA",
    _norm_key("Moskwa"): "RU",
    _norm_key("Mumbaj"): "IN",
    _norm_key("Nairobi"): "KE",
    _norm_key("New Britain"): "US",
    _norm_key("New Delhi"): "IN",
    _norm_key("Newcastle"): "GB",
    _norm_key("Nikozja"): "CY",
    _norm_key("Nottingham"): "GB",
    _norm_key("Nowy Jork"): "US",
    _norm_key("Oslo"): "NO",
    _norm_key("Ostrawa"): "CZ",
    _norm_key("Ottawa"): "CA",
    _norm_key("Pampeluna"): "ES",
    _norm_key("Paryż"): "FR",
    _norm_key("Passaic"): "US",
    _norm_key("Pekin"): "CN",
    _norm_key("Pjongjang"): "KP",
    _norm_key("Podgorica"): "ME",
    _norm_key("Praga"): "CZ",
    _norm_key("Pretoria"): "ZA",
    _norm_key("Rabat"): "MA",
    _norm_key("Reykjavík"): "IS",
    _norm_key("Rijad"): "SA",
    _norm_key("Ryga"): "LV",
    _norm_key("Rzym"): "IT",
    _norm_key("Saloniki"): "GR",
    _norm_key("Sankt Petersburg"): "RU",
    _norm_key("Santiago"): "CL",
    _norm_key("Sarajewo"): "BA",
    _norm_key("Saskatoon"): "CA",
    _norm_key("Seul"): "KR",
    _norm_key("Singapur"): "SG",
    _norm_key("Skopje"): "MK",
    _norm_key("Smoleńsk"): "RU",
    _norm_key("Sofia"): "BG",
    _norm_key("Somerset"): "GB",
    _norm_key("Sousse"): "TN",
    _norm_key("Southampton"): "GB",
    _norm_key("Spalding"): "GB",
    _norm_key("Stambuł"): "TR",
    _norm_key("Stavanger"): "NO",
    _norm_key("Sydney"): "AU",
    _norm_key("Szanghaj"): "CN",
    _norm_key("Sztokholm"): "SE",
    _norm_key("Tajpej"): "TW",
    _norm_key("Tallinn"): "EE",
    _norm_key("Taszkient"): "UZ",
    _norm_key("Tbilisi"): "GE",
    _norm_key("Teheran"): "IR",
    _norm_key("Tel Awiw"): "IL",
    _norm_key("Tirana"): "AL",
    _norm_key("Tokio"): "JP",
    _norm_key("Toronto"): "CA",
    _norm_key("Trondheim"): "NO",
    _norm_key("Trypolis"): "LY",
    _norm_key("Tunis"): "TN",
    _norm_key("Urosevac"): "XK",
    _norm_key("Vancouver"): "CA",
    _norm_key("Walencja"): "ES",
    _norm_key("Waszyngton"): "US",
    _norm_key("Wellington"): "NZ",
    _norm_key("Wiedeń"): "AT",
    _norm_key("Wilno"): "LT",
    _norm_key("Winnipeg"): "CA",
    _norm_key("Zagrzeb"): "HR",
    # Additional city aliases
    _norm_key("Ho Chi Minh"): "VN",
    _norm_key("Lille"): "FR",
    _norm_key("Reykjavik"): "IS",
    _norm_key("Izrael Tel Aviv"): "IL",
    _norm_key("Zimbabwe Harare"): "ZW",
    _norm_key("Harare"): "ZW",
}


_RO_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("Emiratele Arabe Unite"): "AE",
    _norm_key("Australia"): "AU",
    _norm_key("Canada"): "CA",
    _norm_key("Confederatia Elvetiana"): "CH",
    _norm_key("Elvetia"): "CH",
    _norm_key("Bosnia si Hertegovina"): "BA",
    _norm_key("Bosnia si Herzegovina"): "BA",
    _norm_key("Bosnia Hertegovina"): "BA",
    _norm_key("Bosnia Herţegovina"): "BA",
    _norm_key("Bosnia - Herzegovina"): "BA",
    _norm_key("Bosnia-Herzegovina"): "BA",
    _norm_key("Marea Jamahirie Araba Libiana Populara Socialista"): "LY",
    _norm_key("Marele Ducat de Luxemburg"): "LU",
    _norm_key("Regatul Belgiei"): "BE",
    _norm_key("Regatul Danemarcei"): "DK",
    _norm_key("Regatul Norvegiei"): "NO",
    _norm_key("Regatul Spaniei"): "ES",
    _norm_key("Regatul Suediei"): "SE",
    _norm_key("Regatul Unit al Marii Britanii si al Irlandei de Nord"): "GB",
    _norm_key("Regatul Unit al Marii Britanii si al Irlandei"): "GB",
    _norm_key("Regatul Unit al Marii Britanii si Irlandei de Nord"): "GB",
    _norm_key("Republica Federala Nigeria"): "NG",
    _norm_key("Repubica Federala Nigeria"): "NG",
    _norm_key("Republica Afganistan"): "AF",
    _norm_key("Republica Africa de Sud"): "ZA",
    _norm_key("Republica Algeriana Democratica si Populara"): "DZ",
    _norm_key("Republica Angola"): "AO",
    _norm_key("Republica Araba Egipt"): "EG",
    _norm_key("Republica Argentina"): "AR",
    _norm_key("Republica Armenia"): "AM",
    _norm_key("Republica Austria"): "AT",
    _norm_key("Republica Azerbaidjan"): "AZ",
    _norm_key("Republica Bulgaria"): "BG",
    _norm_key("Republica Cuba"): "CU",
    _norm_key("Republica Democratica Socialista Sri Lanka"): "LK",
    _norm_key("Republica Federala Democrata Etiopia"): "ET",
    _norm_key("Republica Federala Germania"): "DE",
    _norm_key("Republica Federativa a Braziliei"): "BR",
    _norm_key("Republica Filipine"): "PH",
    _norm_key("Republica Finlanda"): "FI",
    _norm_key("Republica Franceza"): "FR",
    _norm_key("Republica Irak"): "IQ",
    _norm_key("Republica Italiana"): "IT",
    _norm_key("Republica Kenia"): "KE",
    _norm_key("Republica Lituania"): "LT",
    _norm_key("Republica Mecedonia"): "MK",
    _norm_key("Republica Muntenegru"): "ME",
    _norm_key("Republica Polona"): "PL",
    _norm_key("Republica Populara Democrata Coreeana"): "KP",
    _norm_key("Republica Portugheza"): "PT",
    _norm_key("Republica San Marino"): "SM",
    _norm_key("Republica Senegal"): "SN",
    _norm_key("Republica Slovenia"): "SI",
    _norm_key("Republica Sudan"): "SD",
    _norm_key("Republica Turcia"): "TR",
    _norm_key("Republica Ungara"): "HU",
    _norm_key("Republica Uzbekistan"): "UZ",
    _norm_key("Republica Venezuela"): "VE",
    _norm_key("Republica Zimbabwe"): "ZW",
    _norm_key("Statele Unite Mexicane"): "MX",
    _norm_key("Statul Kuwait"): "KW",
    _norm_key("Statul Quatar"): "QA",
    _norm_key("Marea Jamahirie Araba Libiana Populara Sociali"): "LY",
    _norm_key("Iraq"): "IQ",
    _norm_key("Rep. Coreea"): "KR",
    _norm_key("Rep. Populara Chineza"): "CN",
    _norm_key("RPD Coreeana"): "KP",
    _norm_key("Siria"): "SY",
    _norm_key("Teatrul operatiuni Kosovo"): "XK",
    _norm_key("Bosnia Hertegovina"): "BA",
    _norm_key("Moldova"): "MD",
    _norm_key("Oman"): "OM",
    _norm_key("Republica populara democrata coreeana"): "KP",
}

_FR_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("Amérique du Nord"): "01",
    _norm_key("Amérique latine"): "02",
    _norm_key("Europe du Nord"): "03",
    _norm_key("Benelux"): "04",
    _norm_key("Péninsule ibérique et Monaco"): "05",
    _norm_key("Suisse"): "06",
    _norm_key("Europe centrale"): "07",
    _norm_key("Europe du Sud, Turquie, Israël"): "08",
    _norm_key("Afrique Nord-Ouest"): "09",
    _norm_key("Afrique Centre, Sud et Est"): "10",
    _norm_key("Europe de l'est, Asie, Océanie"): "11",
    _norm_key("Ensemble des Français établis hors de France"): "99",
    _norm_key("Atlanta"): "US",
    _norm_key("Boston"): "US",
    _norm_key("Chicago"): "US",
    _norm_key("Houston"): "US",
    _norm_key("La Nouvelle Orleans"): "US",
    _norm_key("Los Angeles"): "US",
    _norm_key("Miami"): "US",
    _norm_key("Moncton"): "CA",
    _norm_key("Montreal"): "CA",
    _norm_key("New York"): "US",
    _norm_key("Québec"): "CA",
    _norm_key("San Francisco"): "US",
    _norm_key("Toronto"): "CA",
    _norm_key("Vancouver"): "CA",
    _norm_key("Washington"): "US",
    _norm_key("Assomption"): "US",
    _norm_key("Bogota"): "CO",
    _norm_key("Brasilia"): "BR",
    _norm_key("Buenos Aires"): "AR",
    _norm_key("Caracas"): "VE",
    _norm_key("Castries"): "LC",
    _norm_key("Guatemala"): "GT",
    _norm_key("Kingston"): "JM",
    _norm_key("La Havane"): "CU",
    _norm_key("La Paz"): "BO",
    _norm_key("Lima"): "PE",
    _norm_key("Managua"): "NI",
    _norm_key("Mexico"): "MX",
    _norm_key("Montevideo"): "UY",
    _norm_key("Panama"): "PA",
    _norm_key("Paramaribo"): "SR",
    _norm_key("Port-Au-Prince"): "HT",
    _norm_key("Port D'Espagne"): "TT",
    _norm_key("Quito"): "EC",
    _norm_key("Rio De Janeiro"): "BR",
    _norm_key("Saint Domingue"): "DO",
    _norm_key("San Jose"): "CR",
    _norm_key("San Salvador"): "SV",
    _norm_key("Santiago"): "CL",
    _norm_key("Sao Paulo"): "BR",
    _norm_key("Tegucigalpa"): "HN",
    _norm_key("Nassau"): "BS",
    _norm_key("Copenhague"): "DK",
    _norm_key("Dublin"): "IE",
    _norm_key("Edimbourg"): "GB",
    _norm_key("Helsinki"): "FI",
    _norm_key("Londres"): "GB",
    _norm_key("Oslo"): "NO",
    _norm_key("Reykjavik"): "IS",
    _norm_key("Riga"): "LV",
    _norm_key("Stockholm"): "SE",
    _norm_key("Tallinn"): "EE",
    _norm_key("Vilnius"): "LT",
    _norm_key("Amsterdam"): "NL",
    _norm_key("Bruxelles"): "BE",
    _norm_key("Luxembourg"): "LU",
    _norm_key("Andorre"): "AD",
    _norm_key("Barcelone"): "ES",
    _norm_key("Bilbao"): "ES",
    _norm_key("Lisbonne"): "PT",
    _norm_key("Madrid"): "ES",
    _norm_key("Monaco"): "MC",
    _norm_key("Seville"): "ES",
    _norm_key("Geneve"): "CH",
    _norm_key("Zurich"): "CH",
    _norm_key("Belgrade"): "RS",
    _norm_key("Berlin"): "DE",
    _norm_key("Bratislava"): "SK",
    _norm_key("Bucarest"): "RO",
    _norm_key("Budapest"): "HU",
    _norm_key("Cracovie"): "PL",
    _norm_key("Dusseldorf"): "DE",
    _norm_key("Francfort"): "DE",
    _norm_key("Hambourg"): "DE",
    _norm_key("Ljubljana"): "SI",
    _norm_key("Munich"): "DE",
    _norm_key("Podgorica"): "ME",
    _norm_key("Prague"): "CZ",
    _norm_key("Pristina"): "XK",
    _norm_key("Sarajevo"): "BA",
    _norm_key("Sarrebruck"): "DE",
    _norm_key("Skopje"): "MK",
    _norm_key("Sofia"): "BG",
    _norm_key("Stuttgart"): "DE",
    _norm_key("Tirana"): "AL",
    _norm_key("Varsovie"): "PL",
    _norm_key("Vienne"): "AT",
    _norm_key("Zagreb"): "HR",
    _norm_key("Ankara"): "TR",
    _norm_key("Athenes"): "GR",
    _norm_key("Haifa"): "IL",
    _norm_key("Istanbul"): "TR",
    _norm_key("Jerusalem"): "IL",
    _norm_key("La Valette"): "MT",
    _norm_key("Milan"): "IT",
    _norm_key("Naples"): "IT",
    _norm_key("Nicosie"): "CY",
    _norm_key("Rome"): "IT",
    _norm_key("Tel Aviv"): "IL",
    _norm_key("Thessalonique"): "GR",
    _norm_key("Abidjan"): "CI",
    _norm_key("Agadir"): "MA",
    _norm_key("Alger"): "DZ",
    _norm_key("Annaba"): "DZ",
    _norm_key("Bamako"): "ML",
    _norm_key("Bissao"): "GW",
    _norm_key("Casablanca"): "MA",
    _norm_key("Conakry"): "GN",
    _norm_key("Dakar"): "SN",
    _norm_key("Fes"): "MA",
    _norm_key("Marrakech"): "MA",
    _norm_key("Niamey"): "NE",
    _norm_key("Nouakchott"): "MR",
    _norm_key("Oran"): "DZ",
    _norm_key("Ouagadougou"): "BF",
    _norm_key("Praia"): "CV",
    _norm_key("Rabat"): "MA",
    _norm_key("Tanger"): "MA",
    _norm_key("Tripoli"): "LY",
    _norm_key("Tunis"): "TN",
    _norm_key("Abou Dabi"): "AE",
    _norm_key("Abuja"): "NG",
    _norm_key("Accra"): "GH",
    _norm_key("Addis Abeba"): "ET",
    _norm_key("Alexandrie"): "EG",
    _norm_key("Amman"): "JO",
    _norm_key("Bagdad"): "IQ",
    _norm_key("Bangui"): "CF",
    _norm_key("Beyrouth"): "LB",
    _norm_key("Brazzaville"): "CG",
    _norm_key("Bujumbura"): "BI",
    _norm_key("Cotonou"): "BJ",
    _norm_key("Damas"): "SY",
    _norm_key("Dar Es Salam"): "TZ",
    _norm_key("Djeddah"): "SA",
    _norm_key("Djibouti"): "DJ",
    _norm_key("Djouba"): "SS",
    _norm_key("Doha"): "QA",
    _norm_key("Douala"): "CM",
    _norm_key("Dubai"): "AE",
    _norm_key("Erbil"): "IQ",
    _norm_key("Gaborone"): "BW",
    _norm_key("Harare"): "ZW",
    _norm_key("Johannesbourg"): "ZA",
    _norm_key("Kampala"): "UG",
    _norm_key("Khartoum"): "SD",
    _norm_key("Kigali"): "RW",
    _norm_key("Kinshasa"): "CD",
    _norm_key("Koweit"): "KW",
    _norm_key("Lagos"): "NG",
    _norm_key("Le Caire"): "EG",
    _norm_key("Le Cap"): "ZA",
    _norm_key("Libreville"): "GA",
    _norm_key("Lome"): "TG",
    _norm_key("Luanda"): "AO",
    _norm_key("Lusaka"): "ZM",
    _norm_key("Malabo"): "GQ",
    _norm_key("Manama"): "BH",
    _norm_key("Maputo"): "MZ",
    _norm_key("Mascate"): "OM",
    _norm_key("Moroni"): "KM",
    _norm_key("Nairobi"): "KE",
    _norm_key("Ndjamena"): "TD",
    _norm_key("Pointe-Noire"): "CG",
    _norm_key("Port-Louis"): "MU",
    _norm_key("Riyad"): "SA",
    _norm_key("Sanaa"): "YE",
    _norm_key("Tananarive"): "MG",
    _norm_key("Victoria"): "SC",
    _norm_key("Windhoek"): "NA",
    _norm_key("Yaounde"): "CM",
    _norm_key("Achgabat"): "TM",
    _norm_key("Almaty"): "KZ",
    _norm_key("Bakou"): "AZ",
    _norm_key("Bandar Seri Begawan"): "BN",
    _norm_key("Bangalore"): "IN",
    _norm_key("Bangkok"): "TH",
    _norm_key("Bombay"): "IN",
    _norm_key("Calcutta"): "IN",
    _norm_key("Canton"): "CN",
    _norm_key("Chengdu"): "CN",
    _norm_key("Chisinau"): "MD",
    _norm_key("Colombo"): "LK",
    _norm_key("Dacca"): "BD",
    _norm_key("Ekaterinbourg"): "RU",
    _norm_key("Erevan"): "AM",
    _norm_key("Hanoi"): "VN",
    _norm_key("Ho Chi Minh Ville"): "VN",
    _norm_key("Hong Kong"): "HK",
    _norm_key("Islamabad"): "PK",
    _norm_key("Jakarta"): "ID",
    _norm_key("Kaboul"): "AF",
    _norm_key("Karachi"): "PK",
    _norm_key("Katmandou"): "NP",
    _norm_key("Kiev"): "UA",
    _norm_key("Kuala Lumpur"): "MY",
    _norm_key("Kyoto"): "JP",
    _norm_key("Manille"): "PH",
    _norm_key("Minsk"): "BY",
    _norm_key("Moscou"): "RU",
    _norm_key("New Delhi"): "IN",
    _norm_key("Oulan Bator"): "MN",
    _norm_key("Pekin"): "CN",
    _norm_key("Phnom Penh"): "KH",
    _norm_key("Pondichery"): "IN",
    _norm_key("Port Moresby"): "PG",
    _norm_key("Port Vila"): "VU",
    _norm_key("Rangoun"): "MM",
    _norm_key("Saint-Petersbourg"): "RU",
    _norm_key("Seoul"): "KR",
    _norm_key("Shanghai"): "CN",
    _norm_key("Shenyang"): "CN",
    _norm_key("Singapour"): "SG",
    _norm_key("Suva"): "FJ",
    _norm_key("Sydney"): "AU",
    _norm_key("Tachkent"): "UZ",
    _norm_key("Tbilissi"): "GE",
    _norm_key("Teheran"): "IR",
    _norm_key("Tokyo"): "JP",
    _norm_key("Vientiane"): "LA",
    _norm_key("Wellington"): "NZ",
    _norm_key("Wuhan"): "CN",
    _norm_key("Taipeh"): "TW",
    _norm_key("Quebec"): "CA",
    _norm_key("Recife"): "BR",
    _norm_key("Monterrey"): "MX",
    _norm_key("Bahamas (Nassau)"): "BS",
    _norm_key("Taipei"): "TW",
    _norm_key("Nour-Soultan"): "KZ",
    _norm_key("Nur Sultan"): "KZ",
    _norm_key("Astana"): "KZ",
    _norm_key("Mossoul"): "IQ",
    _norm_key("Florence"): "IT",
}

_EL_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("Αίγυπτος"): "EG",
    _norm_key("Αλβανία"): "AL",
    _norm_key("Αυστραλία"): "AU",
    _norm_key("Αυστρία"): "AT",
    _norm_key("Βέλγιο"): "BE",
    _norm_key("Βουλγαρία"): "BG",
    _norm_key("Γαλλία"): "FR",
    _norm_key("Γερμανία"): "DE",
    _norm_key("Δανία"): "DK",
    _norm_key("Ελβετία"): "CH",
    _norm_key("Ηνωμένα Αραβικά Εμιράτα"): "AE",
    _norm_key("Ηνωμένο Βασίλειο"): "GB",
    _norm_key("ΗΠΑ"): "US",
    _norm_key("Ιρλανδία"): "IE",
    _norm_key("Ισπανία"): "ES",
    _norm_key("Ιταλία"): "IT",
    _norm_key("Καναδάς"): "CA",
    _norm_key("Κατάρ"): "QA",
    _norm_key("Κορέα"): "KR",
    _norm_key("Κύπρος"): "CY",
    _norm_key("Λιθουανία"): "LT",
    _norm_key("Λουξεμβούργο"): "LU",
    _norm_key("Μάλτα"): "MT",
    _norm_key("Νορβηγία"): "NO",
    _norm_key("Νότια Αφρική"): "ZA",
    _norm_key("Ολλανδία"): "NL",
    _norm_key("Ουγγαρία"): "HU",
    _norm_key("Πολωνία"): "PL",
    _norm_key("Πορτογαλία"): "PT",
    _norm_key("Ρουμανία"): "RO",
    _norm_key("Σαουδική Αραβία"): "SA",
    _norm_key("Σιγκαπούρη"): "SG",
    _norm_key("Σουηδία"): "SE",
    _norm_key("Τουρκία"): "TR",
    _norm_key("Τσεχία"): "CZ",
    _norm_key("Φινλανδία"): "FI",
}

_IT_COUNTRY_ALIASES: dict[str, str] = {
    _norm_key("ALBANIA"): "AL",
    _norm_key("ANDORRA"): "AD",
    _norm_key("AUSTRIA"): "AT",
    _norm_key("BELGIO"): "BE",
    _norm_key("BULGARIA"): "BG",
    _norm_key("REPUBBLICA CECA"): "CZ",
    _norm_key("STATO CITTA' DEL VATICANO"): "VA",
    _norm_key("DANIMARCA"): "DK",
    _norm_key("FINLANDIA"): "FI",
    _norm_key("FRANCIA"): "FR",
    _norm_key("GERMANIA"): "DE",
    _norm_key("REGNO UNITO"): "GB",
    _norm_key("GRECIA"): "GR",
    _norm_key("IRLANDA"): "IE",
    _norm_key("ISLANDA"): "IS",
    _norm_key("SERBIA"): "RS",
    _norm_key("LIECHTENSTEIN"): "LI",
    _norm_key("LUSSEMBURGO"): "LU",
    _norm_key("MALTA"): "MT",
    _norm_key("MONACO"): "MC",
    _norm_key("NORVEGIA"): "NO",
    _norm_key("PAESI BASSI"): "NL",
    _norm_key("POLONIA"): "PL",
    _norm_key("PORTOGALLO"): "PT",
    _norm_key("ROMANIA"): "RO",
    _norm_key("SAN MARINO"): "SM",
    _norm_key("SPAGNA"): "ES",
    _norm_key("SVEZIA"): "SE",
    _norm_key("SVIZZERA"): "CH",
    _norm_key("UNGHERIA"): "HU",
    _norm_key("FEDERAZIONE RUSSA"): "RU",
    _norm_key("LITUANIA"): "LT",
    _norm_key("LETTONIA"): "LV",
    _norm_key("ESTONIA"): "EE",
    _norm_key("BIELORUSSIA"): "BY",
    _norm_key("UCRAINA"): "UA",
    _norm_key("CROAZIA"): "HR",
    _norm_key("ARGENTINA"): "AR",
    _norm_key("BAHAMAS"): "BS",
    _norm_key("BOLIVIA"): "BO",
    _norm_key("BRASILE"): "BR",
    _norm_key("CANADA"): "CA",
    _norm_key("CILE"): "CL",
    _norm_key("COLOMBIA"): "CO",
    _norm_key("COSTA RICA"): "CR",
    _norm_key("CUBA"): "CU",
    _norm_key("REPUBBLICA DOMINICANA"): "DO",
    _norm_key("EL SALVADOR"): "SV",
    _norm_key("ECUADOR"): "EC",
    _norm_key("GIAMAICA"): "JM",
    _norm_key("GUATEMALA"): "GT",
    _norm_key("HAITI"): "HT",
    _norm_key("HONDURAS"): "HN",
    _norm_key("MESSICO"): "MX",
    _norm_key("NICARAGUA"): "NI",
    _norm_key("PANAMA"): "PA",
    _norm_key("PARAGUAY"): "PY",
    _norm_key("PERU'"): "PE",
    _norm_key("STATI UNITI D'AMERICA"): "US",
    _norm_key("TRINIDAD E TOBAGO"): "TT",
    _norm_key("URUGUAY"): "UY",
    _norm_key("VENEZUELA"): "VE",
    _norm_key("GUYANA"): "GY",
    _norm_key("BARBADOS"): "BB",
    _norm_key("BELIZE"): "BZ",
    _norm_key("SURINAME"): "SR",
    _norm_key("GRENADA"): "GD",
    _norm_key("SAMOA"): "WS",
    _norm_key("TONGA"): "TO",
    _norm_key("VANUATU"): "VU",
    _norm_key("ANTIGUA E BARBUDA"): "AG",
    _norm_key("SAINT LUCIA"): "LC",
    _norm_key("SAINT VINCENT E GRENADINE"): "VC",
    _norm_key("SAINT KITTS E NEVIS"): "KN",
    _norm_key("ARABIA SAUDITA"): "SA",
    _norm_key("AUSTRALIA"): "AU",
    _norm_key("MYANMAR"): "MM",
    _norm_key("CAMBOGIA"): "KH",
    _norm_key("SRI LANKA"): "LK",
    _norm_key("REPUBBLICA POPOLARE CINESE"): "CN",
    _norm_key("CIPRO"): "CY",
    _norm_key("REPUBBLICA DI COREA"): "KR",
    _norm_key("FILIPPINE"): "PH",
    _norm_key("GIAPPONE"): "JP",
    _norm_key("GIORDANIA"): "JO",
    _norm_key("INDIA"): "IN",
    _norm_key("INDONESIA"): "ID",
    _norm_key("IRAN"): "IR",
    _norm_key("IRAQ"): "IQ",
    _norm_key("ISRAELE"): "IL",
    _norm_key("KUWAIT"): "KW",
    _norm_key("LAOS"): "LA",
    _norm_key("LIBANO"): "LB",
    _norm_key("MALAYSIA"): "MY",
    _norm_key("MONGOLIA"): "MN",
    _norm_key("NEPAL"): "NP",
    _norm_key("NUOVA ZELANDA"): "NZ",
    _norm_key("OMAN"): "OM",
    _norm_key("PAKISTAN"): "PK",
    _norm_key("QATAR"): "QA",
    _norm_key("SINGAPORE"): "SG",
    _norm_key("THAILANDIA"): "TH",
    _norm_key("TURCHIA"): "TR",
    _norm_key("VIETNAM"): "VN",
    _norm_key("BANGLADESH"): "BD",  
    _norm_key("FIGI"): "FJ",
    _norm_key("EMIRATI ARABI UNITI"): "AE",
    _norm_key("BAHREIN"): "BH",
    _norm_key("MALDIVE"): "MV",
    _norm_key("PAPUA NUOVA GUINEA"): "PG",
    _norm_key("ISOLE SALOMONE"): "SB",
    _norm_key("TAIWAN"): "TW",
    _norm_key("REPUBBLICA POPOLARE DEMOCRATICA DI COREA"): "KP",
    _norm_key("KAZAKHSTAN"): "KZ",
    _norm_key("UZBEKISTAN"): "UZ",
    _norm_key("ALGERIA"): "DZ",
    _norm_key("BURKINA FASO"): "BF",
    _norm_key("BURUNDI"): "BI",
    _norm_key("CAMERUN"): "CM",
    _norm_key("CONGO"): "CG",
    _norm_key("REPUBBLICA DEMOCRATICA DEL CONGO"): "CD",
    _norm_key("COSTA D'AVORIO"): "CI",
    _norm_key("BENIN"): "BJ",
    _norm_key("ETIOPIA"): "ET",
    _norm_key("GABON"): "GA",
    _norm_key("GAMBIA"): "GM",
    _norm_key("GHANA"): "GH",
    _norm_key("GUINEA"): "GN",
    _norm_key("KENYA"): "KE",
    _norm_key("LIBIA"): "LY",
    _norm_key("MADAGASCAR"): "MG",
    _norm_key("MALAWI"): "MW",
    _norm_key("MALI"): "ML",
    _norm_key("MAROCCO"): "MA",
    _norm_key("MAURITANIA"): "MR",
    _norm_key("NIGER"): "NE",
    _norm_key("NIGERIA"): "NG",
    _norm_key("EGITTO"): "EG",
    _norm_key("ZIMBABWE"): "ZW",
    _norm_key("RUANDA"): "RW",
    _norm_key("SENEGAL"): "SN",
    _norm_key("SIERRA LEONE"): "SL",
    _norm_key("SOMALIA"): "SO",
    _norm_key("SUD AFRICA"): "ZA",
    _norm_key("SUDAN"): "SD",
    _norm_key("TANZANIA"): "TZ",
    _norm_key("TOGO"): "TG",
    _norm_key("TUNISIA"): "TN",
    _norm_key("UGANDA"): "UG",
    _norm_key("ZAMBIA"): "ZM",
    _norm_key("NAMIBIA"): "NA",
    _norm_key("BOTSWANA"): "BW",
    _norm_key("MAURITIUS"): "MU",
    _norm_key("GUINEA EQUATORIALE"): "GQ",
    _norm_key("MOZAMBICO"): "MZ",
    _norm_key("ANGOLA"): "AO",
    _norm_key("GIBUTI"): "DJ",
    _norm_key("SEYCHELLES"): "SC",
    _norm_key("CAPO VERDE"): "CV",
    _norm_key("GUINEA BISSAU"): "GW",
    _norm_key("ESWATINI"): "SZ",
    _norm_key("SAO TOME' E PRINCIPE"): "ST",
    _norm_key("LESOTHO"): "LS",
    _norm_key("SLOVENIA"): "SI",
    _norm_key("BOSNIA-ERZEGOVINA"): "BA",
    _norm_key("SLOVACCHIA"): "SK",
    _norm_key("MACEDONIA DEL NORD"): "MK",
    _norm_key("ARMENIA"): "AM",
    _norm_key("AZERBAIGIAN"): "AZ",
    _norm_key("GEORGIA"): "GE",
    _norm_key("KIRGHIZISTAN"): "KG",
    _norm_key("MOLDOVA"): "MD",
    _norm_key("TAGIKISTAN"): "TJ",
    _norm_key("TURKMENISTAN"): "TM",
    _norm_key("BRUNEI"): "BN",
    _norm_key("ISOLE MARSHALL"): "MH",
    _norm_key("STATI FEDERATI DI MICRONESIA"): "FM",
    _norm_key("PALAU"): "PW",
    _norm_key("TIMOR ORIENTALE"): "TL",
    _norm_key("MONTENEGRO"): "ME",
    _norm_key("KOSOVO"): "XK",
    _norm_key("REPUBBLICA DI SERBIA"): "RS",
    _norm_key("DOMINICA"): "DM",
    _norm_key("CIAD"): "TD",
    _norm_key("REPUBBLICA CENTRAFRICANA"): "CF",
    _norm_key("SWAZILAND"): "SZ",
    _norm_key("ERITREA"): "ER",
    _norm_key("REPUBBLICA DI MACEDONIA"): "MK",
    _norm_key("SANTA SEDE"): "VA",
    _norm_key("STATO DELLA CITTA' DEL VATICANO"): "VA",
    _norm_key("AFGHANISTAN"): "AF",
    _norm_key("SIRIA"): "SY",
    _norm_key("EX REPUBBLICA JUGOSLAVA DI MACEDONIA"): "MK",
    _norm_key("SERBIA E MONTENEGRO"): "RS",
    _norm_key("GRAN BRETAGNA"): "GB",
}




def resolve_foreign_place(home_country: str, place_name: str | None, place_code: str | None) -> ForeignPlaceMatch | None:
    home = str(home_country or "").strip().upper()
    if len(home) != 2:
        return None

    raw_code = str(place_code or "").strip()
    raw_name = str(place_name or "").strip()
    name_key = _norm_key(raw_name)

    # BG 2009-style foreign section codes.
    if home == "BG" and raw_code.startswith("99") and len(raw_code) >= 7:
        host = _BG_2009_PREFIX_TO_HOST.get(raw_code[:7])
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_by_code_prefix",
            )

    # Country-name rows (e.g., BG 2013 abroad section totals).
    if home == "BG" and name_key:
        host = _BG_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )

        # City-name fallback.
        host = _BG_CITY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_city_name",
            )
        
    if home == "PT":
        host = _PT_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )
        
    if home == "HR":
        host = _HR_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )
        
    if home == "IT":
        host = _IT_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )
        
    if home == "PL":
        host = _PL_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )
        # City-name fallback.
        # Normalise before keying: take text before first comma/period, strip
        # trailing Roman numerals or digits (e.g. "Dublin III" → "Dublin").
        city_raw = re.sub(r"[,\.]\s*.*$", "", raw_name).strip()
        city_raw = re.sub(r"\s+[IVXivx\d]+$", "", city_raw).strip()
        city_key = _norm_key(city_raw)
        host = _PL_CITY_ALIASES.get(city_key) or _PL_CITY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_city_name",
            )

    if home == "RO":
        host = _RO_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"ROZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, host),
                reason="matched_foreign_country_name",
            )
        
    if home == "FR":
        host = _FR_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, place_name),
                reason="matched_foreign_country_name",
            )

    if home == "EL":
        host = _EL_COUNTRY_ALIASES.get(name_key)
        if host:
            return ForeignPlaceMatch(
                host_country=host,
                canonical_code=f"{home}_{home}ZZ{host}",
                canonical_name=_COUNTRY_EN_NAME.get(host, raw_name),
                reason="special_foreign_voter_el",
            )

    return None
